steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/eschizoid/gov-cdmx-twitter-sentiment.git']

  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', '--version=tweets']
    dir: 'streaming'

  - name: gcr.io/cloud-builders/gradle
    args: ['build', 'run']

timeout: 1800s